/* NHÁNH: Khảo sát thực địa — sửa/thêm phiếu ở SURVEY */
const SURVEY = [
  {stt:1,date:"08/05/2026",by:"Mai Thúy Hà · QLST Mandarin",comp:"Kohnan",strong:"Nước rửa tay tạo bọt Kirei Kirei; sáp vuốt tóc Gatsby.",display:"Kệ 1-2 cao nhất dễ nhìn, đủ mã hàng, đầy đủ POSM.",price:"Giá tầm trung dễ mua.",staff:"Không có NV tư vấn đứng quầy.",action:"Nhập hàng rửa tay tạo bọt (khách thích tạo bọt hơn gel, giá dễ bán); sáp vuốt tóc đủ POSM phân biệt các dòng dễ tư vấn.",photos:2},
  {stt:2,date:"08/05/2026",by:"Mai Thúy Hà · QLST Mandarin",comp:"Japanshop (Aeon Mall)",strong:"Các dòng UNO (SRM, sáp vuốt tóc, gel dưỡng); dầu gội xả sữa tắm Macherie — nhà mình chỉ bán nguyên sữa tắm và hay đứt hàng.",display:"1 kệ riêng nổi bật, đầy đủ POSM, tem giá KM theo 1 form chuẩn, bắt mắt.",price:"Giá rẻ thu hút.",staff:"Không có NV tư vấn; khách tự mua sắm.",action:"Học cách làm tem giá KM + POSM rõ ràng: dù không có NV tư vấn khách vẫn tự hiểu sản phẩm.",photos:3},
  {stt:3,date:"08/05/2026",by:"Mai Thúy Hà · QLST Mandarin",comp:"AKURUHI Supermarket (Linh Lang)",strong:"Trà Nhật (130-150k), bột giặt 165k, mì tôm hộp/gói giống bên mình nhưng giá cao hơn (82k-210k).",display:"Trưng bày xấu lộn xộn khó nhìn, không tem giá/POSM; một số mã dán giá trực tiếp lên sản phẩm.",price:"Trà, bột giặt, viên giặt giá ngang bên mình; còn lại cao hơn.",staff:"Chào khách bằng tiếng Nhật, không care, không tư vấn.",action:"Bổ sung trà Nhật túi lọc, trà gạo lứt (rất đa dạng, bên mình hay đứt hàng).",photos:7},
  {stt:4,date:"08/05/2026",by:"Mai Thúy Hà · QLST Mandarin",comp:"GYOMU (Linh Lang)",strong:"Mì chính, cốt hầm rẻ hơn; dầu ăn canola KM 3 chai 105k; nước trà giá rẻ; trà tía tô bên mình không có (có khách hỏi); kem Morinaga giá rẻ.",display:"Đầy đủ tem giá, trưng bày giống Winmart+, tem rõ ràng nổi bật.",price:"Giá rẻ.",staff:"Chào khách khi vào, không tư vấn, hỏi mới hỗ trợ.",action:"Học tem giá KM nhỏ gọn dễ nhìn và nổi bật.",photos:8},
  {stt:5,date:"09/05/2026",by:"Lê Thị Thu Lan · QLST T6 Timecity",comp:"Konni 39",strong:"Bán tốt chăm sóc sắc đẹp và TPCN chăm sóc sức khỏe.",display:"Khu vực riêng + POD KM to, nhận diện dễ.",price:"Ngoài giá sale còn để bảng 'Only Konni' để KH chủ động chọn.",staff:"NV không nhiệt tình khi tư vấn.",action:"Bổ sung POD 'Sakuko đề xuất', 'BEST SALE' để KH dễ chọn trong nhiều dòng.",photos:3},
  {stt:6,date:"09/05/2026",by:"Lê Thị Thu Lan · QLST T6 Timecity",comp:"Matsukiyo",strong:"Nhiều dòng mỹ phẩm chăm sóc đa dạng hơn.",display:"Dòng KM đưa lên kệ đầu tiên, POD KM ghi rõ nội dung + mức giảm; hàng độc quyền gắn POD nhận diện.",price:"Giá cao hơn Sakuko, CTKM còn hạn chế.",staff:"NV không tư vấn.",action:"Tăng thêm POD để tăng nhận diện với KH.",photos:4},
  {stt:7,date:"09/05/2026",by:"Lê Thị Thu Lan · QLST T6 Timecity",comp:"Fuji Mart",strong:"Các nhóm gia vị Nhật.",display:"Để đầu kệ.",price:"Thể hiện rõ % giảm và giá gốc → giá sale.",staff:"NV không tư vấn.",action:"— (chưa ghi)",photos:2},
  {stt:8,date:"10/05/2026",by:"Đỗ Văn Duy · QLST Linh Đàm",comp:"Fujimart, Aeon",strong:"Nhóm chế biến (ăn sẵn, sushi, rau củ, bánh mì); thực phẩm khô (dầu ăn, mì, rong biển).",display:"Đa dạng; SP key bán chạy giá KM tốt trưng ụ gần lối vào; POP in màu + chạy đèn LED.",price:"Nhóm CSSĐ (dầu gội, sữa tắm, nhuộm tóc) giá tốt hơn SKK.",staff:"NV ít tiếp cận khách.",action:"Xem lại giá dầu gội, sữa tắm, collagen... SKK đang cao hơn.",photos:43},
  {stt:9,date:"11/05/2026",by:"Đinh Phương Trang · QLST Hàng Bông",comp:"CP Mart (KĐT Trung Yên)",strong:"TPCN Orihiro bán tốt (giá rẻ hơn 50-70k); nhóm chưa có tại Sakuko chủ yếu TPCN không chính ngạch.",display:"Chủ yếu bán buôn/khách quen, không chú trọng trưng bày.",price:"Rẻ hơn, không có chương trình KM.",staff:"NV chỉ hỏi chị cần sản phẩm gì.",action:"Không nhiều để học vì chủ yếu bán buôn.",photos:1},
  {stt:10,date:"11/05/2026",by:"Đinh Phương Trang · QLST Hàng Bông",comp:"Vườn của bé (Minh Khai)",strong:"Bỉm Moony trắng hàng công ty + hàng rẻ Goldgi (đề xuất ngành hàng nghiên cứu); sữa ngang hệ thống (5-10k); TPCN không chính ngạch bán chạy (cảm cúm, nhỏ mắt).",display:"Trưng ụ, đảo đầu kệ; 100% NV mời khách khi vào về SP chủ chốt.",price:"Combo sữa/bỉm rẻ hơn 10-15k/hộp; có miniapp up SP+CTKM gửi link hàng tháng; catalogue mua kèm treo đầu kệ; giờ vàng giá sốc 11h-14h.",staff:"NV có kiến thức cơ bản, được đào tạo tiếp cận khách.",action:"Triển khai combo sữa/bỉm hoặc giá cả thùng; triển khai giờ vàng để tăng tần suất khách / vào miniapp.",photos:1},
  {stt:11,date:"29/05/2026",by:"Mai Thúy Hà · QLST Mandarin",comp:"Tomita Mart",strong:"Hàng tiêu dùng tươi sống hàng ngày; mới nhập đồ lót, đồ bơi, kính bơi, lọ chiết mỹ phẩm; gia dụng đắt hơn.",display:"Dàn trải, không POSM, không CTKM.",price:"Giá chưa giảm ngang giá bên mình đang giảm; không combo; nổi bật: khách đi 1 nơi đủ đồ như đi chợ.",staff:"NV không tư vấn/mời hàng, hỏi mới trả lời.",action:"Vào mùa bổ sung hàng du lịch: kem, nước, sữa chua, lọ chiết, kính bơi, bọc chống nước ĐT, giặt xả nhiều mã, dép trong nhà, cọ rửa toilet — khách hỏi nhiều mà mình chưa đa dạng.",photos:10},
  {stt:12,date:"01/06/2026",by:"Đỗ Thị Thu Trà · QLST Trần Duy Hưng",comp:"Japanmart (BT4 KĐT Xa La)",strong:"Nhóm thực phẩm và TPCN.",display:"Bày gần quầy thu ngân + đầu lối vào; bán cả hàng TQ, Nga, Úc, VN; lộn xộn, mã nhiều để lẫn — kiểu 'trưng đủ hàng' hơn 'trưng để bán'.",price:"Rẻ hơn 20-30% (giá gốc chưa sale); hàng cận date in tem giá sale trực tiếp; nhiều tay treo ở đầu kệ.",staff:"2 NV, có khách thì ra hỏi tìm SP gì.",action:"Có thể điều chỉnh giá cho phù hợp hơn.",photos:24},
  {stt:13,date:"01/06/2026",by:"Trần Thị Thu Hoàn · ST Linh Đàm",comp:"Pharmacity",strong:"Mỹ phẩm, TPCN Úc, vitamin dạng nước cho bé, kem rạn da, KCN cho bé.",display:"Kệ trắng, đèn LED, kệ chạy dài cùng nhãn hàng + công dụng.",price:"SP xêm xêm, có cái đắt/rẻ hơn; không pop tem giá hay CTKM.",staff:"Nhiệt tình lắng nghe khách.",action:"Học hệ thống đèn/ánh sáng kệ nổi bật hơn.",photos:5},
  {stt:14,date:"02/06/2026",by:"Phạm Thị Minh Ngọc · QLST Nguyễn Du",comp:"Guardian",strong:"TPCN (Blackmores, DHC) giá KM thấp hơn SKK.",display:"Tag đỏ nhỏ ghi 'Tiết kiệm 10/20/30%' + tem giá KM vàng theo từng SP.",price:"Các kệ đều có tem giá KM % nổi bật.",staff:"NV có lúc không care khách; thu ngân hỏi thông tin thành viên.",action:"— (đánh giá 0)",photos:3},
  {stt:15,date:"02/06/2026",by:"Trần Thị Uyên · QLST Thái Hà",comp:"Beauty Box (Royal City)",strong:"Make up, tắm gội, dưỡng da.",display:"Đẹp theo nhãn hàng/bộ SP; kệ mica trong suốt có đèn LED, kệ gỗ có LED kèm sample, rất thu hút.",price:"CTKM theo combo, giảm giá sốc, tem KM đẹp dễ nhìn.",staff:"NV chưa tiếp cận/mời chào như Sakuko.",action:"Mở thêm make up (cushion, bông mút); đầu tư 1-2 kệ mica bày SP theo bộ kèm hàng test.",photos:1},
  {stt:16,date:"02/06/2026",by:"Trần Thị Uyên · QLST Thái Hà",comp:"Matsukiyo",strong:"CSSK ít mã hơn Sakuko giá tương đương, nhiều SP rẻ hơn 30-40k; răng miệng + BVS đa dạng; nhóm nam, nhuộm tóc đa dạng hơn (nhuộm thời trang, nhuộm gói Hàn nhiều màu).",display:"Theo nhóm hàng, theo brand.",price:"Tem KM rõ nổi bật, màu đỏ vàng thu hút.",staff:"NV chưa nhiệt tình, không tiếp cận khách.",action:"Nhập thêm nhuộm thời trang, nhuộm gói; lăn nách nam; sữa tắm Diane mẫu mới đẹp làm quà tặng.",photos:3},
  {stt:17,date:"03/06/2026",by:"Nguyễn Bích Ngọc · QLST Văn Phú",comp:"Guardian",strong:"Chăm sóc sắc đẹp, SRM, KCN, các loại mặt nạ.",display:"Pop KM nền đỏ, ánh sáng đẹp, giá kệ đẹp.",price:"Glucosamin hộp bé 436k; SRM Senka 105k; ý dĩ rẻ hơn 59k; KCN Anessa 491k.",staff:"NV chỉ chỗ và nói đó là top bán chạy.",action:"Dùng túi giấy, để ngay sau quầy thu ngân.",photos:4},
  {stt:18,date:"03/06/2026",by:"Nguyễn Bích Ngọc · QLST Văn Phú",comp:"Kohnan Japan",strong:"Thực phẩm, đồ gia dụng rất đa dạng.",display:"Pop chữ đỏ nền vàng, in công dụng SP lên A5 để quầy với SP chủ đạo.",price:"CSSĐ, sữa tắm, KCN, xịt khoáng, DHC vitamin giá tốt; collagen có dòng hơn 300k.",staff:"Đông khách, khách tự tìm, không thấy NV.",action:"Trưng bày sáng, tất cả bằng mâm kệ, hàng đa dạng nhiều lựa chọn.",photos:6},
  {stt:19,date:"07/06/2026",by:"Bùi Thị Thanh Giang · QLST Bạch Mai",comp:"Hanaichi Store (Tạ Quang Bửu, cách 700m)",strong:"Chủ yếu TPCN (đa số không chính ngạch), mỹ phẩm (không tem phụ).",display:"Diện tích nhỏ, không thu hút; tem giá phông chữ nổi bật; hàng thiếu tem chuẩn thì dán giá trực tiếp.",price:"Giá gốc siêu rẻ (rẻ hơn cả khi mình chạy CTKM); nhiều mặt hàng bên mình chỉ đặt khi có yêu cầu thì nó sẵn kệ; giảm trực tiếp SP, không combo.",staff:"Chỉ 1 NV, bận đóng hàng online không chào; 16h không có khách.",action:"Điều chỉnh giá sốc mặt hàng chức năng; mở thêm SP mùa vụ: kính bơi, giấy thấm mồ hôi, tẩy lông.",photos:8},
  {stt:20,date:"07/06/2026",by:"Bùi Thị Thanh Giang · QLST Bạch Mai",comp:"Konni 39 (106 Bạch Mai, cách 950m)",strong:"Bigen nhuộm tóc giá tốt hơn, có thêm màu cam nhà mình không có.",display:"Theo chức năng SP; POSM TPCN có A5; chỉ bán hàng Nhật, ít gia dụng.",price:"Giá gốc nhiều SP rẻ hơn giá mình đã sale; hàng GH có tem phụ xách tay trưng nhiều; hàng Orihiro giá rất tốt dù không sale; không combo, giảm trực tiếp SP.",staff:"NV không đồng phục, chào 'Konni xin chào'; bám hỏi nhu cầu nhưng không hiểu SP nên không tư vấn nhiều.",action:"Rà soát CTKM chạy giá tốt hơn.",photos:7},
  {stt:21,date:"17/06/2026",by:"Đoàn Văn Khoa · QLST Nguyễn Khuyến",comp:"Kids Plaza",strong:"Các dòng sữa uống hộp mút.",display:"Đa dạng SP, nhiều sữa, nhiều lựa chọn.",price:"Giá sữa còn đắt hơn bên mình.",staff:"NV chỉ chào khi vào, ít tiếp cận khách.",action:"Có thể bán thêm các dòng sữa lốc uống.",photos:0},
  {stt:22,date:"17/06/2026",by:"Đoàn Văn Khoa · QLST Nguyễn Khuyến",comp:"Sói Biển",strong:"Mạnh về thực phẩm và rau củ quả.",display:"Bừa bộn, giá để lung tung.",price:"Một số SP Nhật giá cao.",staff:"NV chưa tiếp cận khách.",action:"— (đánh giá 0)",photos:0}
];
function viewSurvey(){
  const S=SURVEY;
  const comps=[...new Set(S.map(x=>x.comp))].length;
  const surveyors=[...new Set(S.map(x=>x.by))].length;
  const rows=(kw)=>{
    kw=(kw||"").trim().toLowerCase();
    return S.filter(x=>!kw || (x.comp+" "+x.by+" "+x.strong+" "+x.display+" "+x.price+" "+x.staff+" "+x.action).toLowerCase().includes(kw))
      .map(x=>`<div class="mod sv-card">
        <div class="m-top"><span class="code">#${x.stt}</span><span class="m-title">${escapeHtml(x.comp)}</span>
          <span class="m-meta">${x.date} · ${escapeHtml(x.by)}${x.photos?` · 📷 ${x.photos} ảnh`:""}</span></div>
        <div class="sv-grid">
          <div><span class="sv-k">🟥 Bán mạnh / mình chưa có:</span> ${escapeHtml(x.strong)}</div>
          <div><span class="sv-k">🏷️ Trưng bày & làm nổi bật:</span> ${escapeHtml(x.display)}</div>
          <div><span class="sv-k">💰 Giá & CTKM:</span> ${escapeHtml(x.price)}</div>
          <div><span class="sv-k">🧑‍💼 Cách NV bán:</span> ${escapeHtml(x.staff)}</div>
          <div class="sv-act"><span class="sv-k">✅ Đề xuất áp dụng ngay:</span> ${escapeHtml(x.action)}</div>
        </div></div>`).join("");
  };
  setTimeout(()=>{const i=$("#svQ");if(i)i.oninput=()=>{$("#svList").innerHTML=rows(i.value); $("#svCount").textContent=$("#svList").querySelectorAll(".sv-card").length;};},0);
  return `
  <div class="card"><h2>🔍 Khảo sát thực địa đối thủ</h2>
    <p class="lead">Data gốc do QLST các CH đi khảo sát trực tiếp (${S.length} phiếu · ${comps} đối thủ · ${surveyors} người khảo sát). Dành cho <b>chuyên viên ngành hàng</b> khai thác: mã hàng đối thủ mạnh mà Sakuko chưa có, cách trưng bày/POSM, giá & CTKM, đề xuất hành động.</p>
    <input id="svQ" placeholder="🔎 Tìm theo đối thủ, nhóm hàng, từ khóa... (vd: nhuộm, TPCN, tem giá, combo)" style="margin-top:6px">
    <div class="lead" style="margin-top:8px">Đang hiển thị <b id="svCount">${S.length}</b> phiếu.</div>
  </div>
  <div id="svList">${rows("")}</div>`;
}
registerTab({ id:"survey", label:"Khảo sát thực địa", render:viewSurvey });
